fullname: database-deployment
replicaCount: 3
labels: database
image:
  repository: postgres
  tag: "11.22-bullseye"
containerPort: 5432
containerName: database
containerMemory: "4Gi"
containerCpu: "1"